# Generated by Django 4.1.3 on 2022-11-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='a',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='b',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='c',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='d',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
