# Generated by Django 4.1.3 on 2022-11-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0002_questions_a_questions_b_questions_c_questions_d'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
