# Generated by Django 4.1.3 on 2022-12-01 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('npp',), 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ('npp',), 'verbose_name': 'тест', 'verbose_name_plural': 'тесты'},
        ),
    ]
